/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

public class Day01 extends PuzzleDay {
    public Day01(String puzzleInput) {
        super(puzzleInput);
    }

    public int getDay() {
        return 1;
    }

    protected void solvePuzzle(String s) {
        int count = 0;
        boolean basementFound = false;
        int totalLength = s.length();

        if (s.length() < 1) {
            return;
        }
        
        do {
            if (s.charAt(0) == '(') {
                count++;
            } else if (s.charAt(0) == ')') {
                count--;
            } else {
                System.err.println("Invalid character '" + s.charAt(0) + "' in input! Cannot proceed.");
                System.exit(1);
            }
            s = s.substring(1, s.length());
            if (!basementFound && count < 0) {
                basementFound = true;
                this.partTwoAnswer = String.valueOf(totalLength - s.length());
            }
        } while (s.length() >= 1);
        
        this.partOneAnswer = String.valueOf(count);
    }
}
