/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

public class Day01 {
    public String part1(String input) {
        return "0";
    }

    public Day01() {
    }
}
