/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

public class Day18 extends PuzzleDay {
    public Day18(String puzzleInput) {
        super(puzzleInput);
    }

    public int getDay() {
        return 3;
    }

    protected void solvePuzzle(String s) {
        this.partOneAnswer = "";
        this.partTwoAnswer = "";
    }
}
