/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.LinkedList;


public class TestApp {
    private LinkedList<HashMap<String,String>> tests;

    @Test public void testDay01() {
        TestCase t = new TestCase();
        t.add("(())","0");
        t.add("()()","0");
        t.add("(((","3");
        t.add("(()(()(","3");
        t.add("))(((((","3");
        t.add("())","-1");
        t.add("))(","-1");
        t.add(")))","-3");
        t.add(")())())","-3");
        this.tests = t.getTests();

        Day01 d1 = new Day01();
        for (HashMap<String,String> c : this.tests){
            String input = c.get("input");
            String output = d1.part1(input);
            String expectedOutput = c.get("output");
            assertEquals("Test case failed! Input: " + input, expectedOutput, output);
        }
    }
}
